title: Project

files:
  sortable: true

pages: false

fields:
  title:
    label: Title
    type:  text
    width: 2/3

  coverImage:
    label: Cover Image
    type:  image
    width: 1/3

  tags:
    label: Tags
    type: multiselect
    required: true
    search: true
    options:
      Art Direction: Art Direction
      brandIdentity: Brand Identity
      Campaigns: Campaigns
      Digital Design: Digital Design
      Exhibition Design: Exhibition Design
      Packaging: Packaging
      Photography: Photography
      Space Design: Space Design

  builder:
      label: Case Study
      type: builder
      fieldsets:
        jumbotron:
          label: Jumbotron
          snippet: caseStudy/jumbotron
          fields:
            picture:
              label: Image
              type: image
        fullText:
          label: Text
          snippet: caseStudy/fullText
          fields:
            text:
              label: Text
              type: textarea
        fullImage:
          label: Full Width Image
          snippet: caseStudy/fullImage
          fields:
            picture:
              label: Image
              type: image
        textText:
          label: Text | Text
          snippet: caseStudy/textText
          fields:
            text1:
              label: Text Left
              type: textarea
              width: 1/2
            text2:
              label: Text Right
              type: textarea
              width: 1/2
        imageImage:
          label: Image | Image
          snippet: caseStudy/imageImage
          fields:
            picture1:
              label: Image Left
              type: image
              width: 1/2
            picture2:
              label: Image Right
              type: image
              width: 1/2
        imageText:
          label: Image | Text
          snippet: caseStudy/imageText
          fields:
            picture:
              label: Image
              type: image
              width: 1/2
            text:
              label: Text
              type: textarea
              width: 1/2
        textImage:
          label: Text | Image
          entry: {{url}}
          snippet: caseStudy/textImage
          fields:
            text:
              label: Text
              type: textarea
              width: 1/2
            picture:
              label: Image
              type: image
              width: 1/2
