title: Project

files:
  sortable: true

pages: false

fields:
  title:
    label: Title
    type:  text
    width: 2/3

  coverImage:
    label: Cover Image
    type:  image
    width: 1/3

  tags:
    label: Tags
    type: multiselect
    required: true
    search: true
    options:
      Art Direction: Art Direction
      brandIdentity: Brand Identity
      Campaigns: Campaigns
      Digital Design: Digital Design
      Exhibition Design: Exhibition Design
      Packaging: Packaging
      Photography: Photography
      Space Design: Space Design

  builder:
      label: Case Study
      type: builder
      fieldsets:
        jumbotron:
          label: Jumbotron
          snippet: sections/bodytext
          fields:
            text:
              label: text
              type: textarea
        image:
          label: Image
          snippet: sections/imagebanner
          fields:
            picture:
              label: Background Image
              type: image
            text:
              label: Headline Text
              type: text
        quote:
          label: Quote
          snippet: sections/quote
          fields:
            text:
              label: Quote Text
              type: textarea
            citation:
              label: Citation
              type: text
