title: Site

pages: default

fields:
  title:
    label: Title
    type:  text

  description:
    label: Description
    type:  textarea

  copyright:
    label: Copyright
    type:  textarea

  keywords:
    label: Keywords
    type:  text

  facebook:
    label: facebook
    type:  text

  twitter:
    label: twitter
    type:  text

  instagram:
    label: instagram
    type:  text

  behance:
    label: behance
    type:  text
